hasCJKLanguage = true
baseUrl = 'https://blog.ondorg.ru/'
languageCode = 'ru-ru'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = 'public'
MetaDataFormat = "toml"
paginate = 9
copyright = "© 2017 PPAP blog powered by Hugo"
